// Static fallback products list for build-time generation
export const FALLBACK_PRODUCTS = [
    'Apples, per kilogram',
    'Bananas, per kilogram',
    'Bread, 675 grams',
    'Milk, 1 litre',
    'Eggs, 12 count',
    'Chicken, per kilogram',
    'Beef, per kilogram',
    'Rice, 2 kilograms',
    'Pasta, 500 grams',
    'Cheese, 500 grams',
    'Butter, 454 grams',
    'Potatoes, per kilogram',
    'Tomatoes, per kilogram',
    'Onions, per kilogram',
    'Carrots, per kilogram',
    'Broccoli, unit',
    'Cucumber, unit',
    'Lettuce, unit',
    'Spinach, 340 grams',
    'Grapes, per kilogram',
    'Strawberries, 454 grams',
    'Oranges, per kilogram',
    'Lemons, unit',
    'Limes, unit',
    'Avocados, unit',
    'Bell peppers, unit',
    'Mushrooms, 227 grams',
    'Green beans, 454 grams',
    'Corn, 4 ears',
    'Peas, 454 grams',
    'Asparagus, 454 grams',
    'Cauliflower, unit',
    'Cabbage, per kilogram',
    'Sweet potatoes, per kilogram',
    'Garlic, unit',
    'Ginger, unit',
    'Honey, 500 grams',
    'Maple syrup, 500 millilitres',
    'Olive oil, 1 litre',
    'Vegetable oil, 3 litres',
    'Vinegar, 1 litre',
    'Soy sauce, 500 millilitres',
    'Ketchup, 1 litre',
    'Mustard, 500 millilitres',
    'Mayonnaise, 890 millilitres',
    'Peanut butter, 500 grams',
    'Jam, 500 grams',
    'Cereal, 500 grams',
    'Oatmeal, 1 kilogram',
    'Flour, 2.5 kilograms',
    'Sugar, 2 kilograms',
    'Salt, 1 kilogram',
    'Black pepper, 100 grams',
    'Cinnamon, 100 grams',
    'Vanilla extract, 100 millilitres',
    'Baking powder, 500 grams',
    'Baking soda, 500 grams',
    'Yeast, 100 grams',
    'Chocolate chips, 500 grams',
    'Nuts, 500 grams',
    'Dried fruits, 500 grams',
    'Crackers, 200 grams',
    'Cookies, 500 grams',
    'Ice cream, 1 litre',
    'Yogurt, 500 grams',
    'Cream, 1 litre',
    'Sour cream, 500 grams',
    'Cottage cheese, 500 grams',
    'Cream cheese, 250 grams',
    'Feta cheese, 200 grams',
    'Parmesan cheese, 200 grams',
    'Mozzarella cheese, 500 grams',
    'Cheddar cheese, 500 grams',
    'Swiss cheese, 500 grams',
    'Provolone cheese, 500 grams',
    'Gouda cheese, 500 grams',
    'Brie cheese, 200 grams',
    'Camembert cheese, 200 grams',
    'Blue cheese, 200 grams',
    'Goat cheese, 200 grams',
    'Ricotta cheese, 500 grams',
    'Mascarpone cheese, 250 grams',
    'Halloumi cheese, 250 grams',
    'Paneer cheese, 500 grams',
    'Tofu, 350 grams',
    'Tempeh, 500 grams',
    'Seitan, 500 grams',
    'Veggie burgers, 226 grams',
    'Plant-based milk, 1 litre',
    'Plant-based yogurt, 500 grams',
    'Plant-based cheese, 200 grams',
    'Plant-based butter, 454 grams',
    'Plant-based cream, 500 millilitres',
    'Plant-based ice cream, 1 litre',
    'Plant-based meat, 500 grams',
    'Plant-based sausages, 400 grams',
    'Plant-based bacon, 200 grams',
    'Plant-based chicken, 500 grams',
    'Plant-based fish, 500 grams',
    'Plant-based eggs, 12 count',
    'Plant-based mayo, 500 millilitres',
    'Plant-based sour cream, 500 grams',
    'Plant-based cream cheese, 250 grams',
    'Plant-based parmesan, 200 grams',
    'Plant-based mozzarella, 500 grams',
    'Plant-based cheddar, 500 grams',
    'Plant-based gouda, 500 grams',
    'Plant-based brie, 200 grams',
    'Plant-based blue cheese, 200 grams',
    'Plant-based goat cheese, 200 grams',
    'Plant-based ricotta, 500 grams',
    'Plant-based mascarpone, 250 grams',
    'Plant-based halloumi, 250 grams',
    'Plant-based paneer, 500 grams',
    'Plant-based tofu, 350 grams',
    'Plant-based tempeh, 500 grams',
    'Plant-based seitan, 500 grams',
    'Plant-based veggie burgers, 226 grams',
    'Plant-based plant milk, 1 litre',
    'Plant-based plant yogurt, 500 grams',
    'Plant-based plant cheese, 200 grams',
    'Plant-based plant butter, 454 grams',
    'Plant-based plant cream, 500 millilitres',
    'Plant-based plant ice cream, 1 litre',
    'Plant-based plant meat, 500 grams',
    'Plant-based plant sausages, 400 grams',
    'Plant-based plant bacon, 200 grams',
    'Plant-based plant chicken, 500 grams',
    'Plant-based plant fish, 500 grams',
    'Plant-based plant eggs, 12 count',
    'Plant-based plant mayo, 500 millilitres',
    'Plant-based plant sour cream, 500 grams',
    'Plant-based plant cream cheese, 250 grams',
    'Plant-based plant parmesan, 200 grams',
    'Plant-based plant mozzarella, 500 grams',
    'Plant-based plant cheddar, 500 grams',
    'Plant-based plant gouda, 500 grams',
    'Plant-based plant brie, 200 grams',
    'Plant-based plant blue cheese, 200 grams',
    'Plant-based plant goat cheese, 200 grams',
    'Plant-based plant ricotta, 500 grams',
    'Plant-based plant mascarpone, 250 grams',
    'Plant-based plant halloumi, 250 grams',
    'Plant-based plant paneer, 500 grams'
]; 